### ISSUE TITLE
Use regex for requirements patterns

### ISSUE THREAD

**Issue by batal1** [hpenne/asciireqs#10]
Hello,

I tried your tool, and I like it, I think it is a very nice way of solving traceability matrix hell.
But as soon as I tried to change the {req-prefix} to make it comply with my needs, it did not work anymore.
Do you think it would be possible to use regex instead of fixed string for requirements prefix ?
Thanks,
Alain

**Comment by hpenne** [comment]
Alain,

I'm glad to hear that you liked it.  I prototyped this in frustration over the poor change and configuration management of the tool that I'm currently forced to use at work.  The goal was to show that it was possible to move everything into git and still get reasonable requirements tracing and decent documents.  I also did it to improve my limited Python skills a little.

Please note that this is just a prototype.  I would not recommend using it professionally unless you intend to do some maintenance and bugfixes yourself.  I'm not doing any work on it at the moment, and I'm not aware of anyone using it professionally.

Anyway, I will look into your suggestion about using regex to find requirement identifiers.  It sounds like a good idea.

Best regards,
Helge Penne

**Comment by batal1** [comment]
Helge,

Thank you for your reply. We do not use any tool at work to manage requirements, so any improvement, even using a prototype (as you call it) would be appreciated (at least by me, as I have to manually check for requirements across documents)
I am pushing to use Asciidoctor for documentation writing instead of MS Word, and that's how I found your project which I find really handy.
Thans again,
Alain

**Comment by hpenne** [comment]
Alain,

I have published a new version (0.0.7) which you can try out ("pip install --upgrade asciireqs").  The "pre-prefix" attribute has been replaced with "req-regex" (see the Readme for details).  All the test still pass, but I have not tested it beyond that.

Best regards,
Helge

**Comment by batal1** [comment]
Hello Helge,

I updated my version of asciireqs, and made a few tests, and everything now works like a charm !
Thanks a lot, I think I'll be able to use it to comply with my constraints.
Again, you did a great job, indeed !
Thanks !

**Comment by batal1** [comment]
Works perfectly
