### ISSUE TITLE
Test drive fails

### ISSUE THREAD

**Issue by owbear** [hpenne/asciireqs#11]
Using Python 3.12.3 on Ubuntu 24.04.1 LTS

Running `asciireq -o ../output -t report-template req-tool-user-reqs.adoc` as shown in README.adoc results in:

> FileNotFoundError: [Errno 2] No such file or directory: 'report-template'

`asciireq -o ../output -t report-template.adoc req-tool-user-reqs.adoc` works but produces incorrect output as show by `git diff ../output/req-tool-user-reqs.adoc`:

```
diff --git a/output/req-tool-user-reqs.adoc b/output/req-tool-user-reqs.adoc
index 6809d274..7027e2c6 100644
--- a/output/req-tool-user-reqs.adoc
+++ b/output/req-tool-user-reqs.adoc
@@ -5,7 +5,7 @@
 :sectnumlevels: 3
 :disclosure: Internal
 :req-children: req-tool-sw-reqs.adoc
-:req-prefix: UR-RMS-REQ-
+:req_regex: UR-RMS-REQ-\d+
 
 This is a page after the cover, where approval and history will go.
 
@@ -29,7 +29,7 @@ Requirements are written as AsciiDoc "terms":
 The SW shall support an centrally hosted data store.
 +
 Tags: Rel-1;
-Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-011[SW-RMS-REQ-011]
+Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-0[SW-RMS-REQ-0]11
 
 [[UR-RMS-REQ-012]]UR-RMS-REQ-012::
 The SW shall support versioning and baselining.
@@ -51,7 +51,7 @@ Tags: Rel-2
 [[UR-RMS-REQ-021]]UR-RMS-REQ-021::
 The SW shall support hierarchical specifications documents, and links between parent and child requirements.
 +
-Tags: Rel-1; Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-021[SW-RMS-REQ-021]
+Tags: Rel-1; Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-0[SW-RMS-REQ-0]21
```

**Comment by owbear** [comment]
I get the same results with Docker image python:3.8.5-slim-buster

Details:
```
root@2c6e90c17d4c:/app/testdata# python -V
Python 3.8.5
root@2c6e90c17d4c:/app/testdata# pip freeze
asciireqs==0.0.7
et-xmlfile==2.0.0
mypy==1.13.0
mypy-extensions==1.0.0
openpyxl==3.1.5
openpyxl-stubs==0.1.25
PyYAML==5.4.1
tomli==2.1.0
types-PyYAML==6.0.12.20240917
typing-extensions==4.12.2
```

**Comment by hpenne** [comment]
Thank you for reporting this. I have not had time to confirm yet, but this is most likely two different things:
1) The doc is wrong, and you should use the full file name of the template.
2) I forgot to update the reference file when I replaced "req-prefix" with "req_regex" in the last version (so the test is wrong, not the code).

I'll investiagate to confirm.  In the mean time, I think everything should work as usual if you use the full name of the template file.

**Comment by owbear** [comment]
Yeah, you're right; testdata/ and code was updated in "Changed from using req_prefix to req_regex" but not output/

The problem I'm having is the broken links, SW-RMS-**REQ-011**[...] is rewritten as SW-RMS-**REQ-0**[...]**11**:

```
@@ -29,7 +29,7 @@ Requirements are written as AsciiDoc "terms":
 The SW shall support an centrally hosted data store.
 +
 Tags: Rel-1;
-Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-011[SW-RMS-REQ-011]
+Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-0[SW-RMS-REQ-0]11
```

**Comment by owbear** [comment]
There was a problem with the `req_regex` in sw-reqs. This solves the problem:

```
--- a/testdata/req-tool-sw-reqs.adoc
+++ b/testdata/req-tool-sw-reqs.adoc
@@ -4,7 +4,7 @@
 :sectnums:
 :sectnumlevels: 3
 :disclosure: Internal
-:req_regex: SW-RMS-REQ-\d
+:req_regex: SW-RMS-REQ-\d+
```

**Comment by hpenne** [comment]
@owbear Thanks for the PR for this. I've merged it, verified that the example command generates the expected output (no diff) and pushed a new version to PyPi. I fumbled the first attempt at publishing so it ended up as 0.0.9 instead of 0.0.8...
